include: "rules/common.smk"
include: "rules/sources.smk"
include: "rules/peaks.smk"
include: "rules/zscore.smk"
include: "rules/ccres.smk"


rule all:
    input:
        f"{RESULTS_DIR}/{PREFIX}_{GENOME}-Anchors-ATAC.bed",
        # intermediate_bw_files,
        # intermediate_DNase_files,
        f"{RESULTS_DIR}/{PREFIX}_{GENOME}-ATAC-maxZ.txt",
        f"{RESULTS_DIR}/{PREFIX}_{GENOME}-DNase-maxZ.txt",
        f"{RESULTS_DIR}/{PREFIX}_{GENOME}-cCREs.bed",
