# ENCODE call ATAC based cCRES config.yaml

# move the encode dnase next to encode atac
# GLOBAL VARs 
ENCODE_data_included: True
encode_atac_list: "resources/encode-atac.2026-09-23.legacy.txt"

encode_DNase_list: "resources/ENCODE-DNase-List.txt"

CUSTOM_data_included: TRUE
CUSTOM_data_macs_info: "resources/CUSTOM_ATAC_List_narrowpeaks_2026-08-25_0.2_25000000_orbonus_50per.txt" # tab delimed file;  sample \t file_location
CUSTOM_data_bw_info: "resources/CUSTOM_ATAC_List_bw_2026-08-25_0.2_25000000_orbonus_50per.txt" # tab delimed file;  sample \t file_location
CUSTOM_track_ini: 'resources/CUSTOM_track.ini'

ccre_path: "resources/GRCh38-cCREs.bed"
rdhs_path: "resources/GRCh38-Anchors.bed"
mappable: "resources/k100.Unique.Mappability.bed" 

save_intermediates: True
genome: "hg38"
filter_FRIP: 0.2 # zero point 2
filter_min_reads: 25 # 25 mill 

# 
work_dir: "."
ouput_dir: "/zata/zippy/ramirezc/ccre-golden/merged"
log_dir: "/zata/zippy/ramirezc/ccre-golden/merged/logs"
tmp_dir: "/tmp"
TOOLKIT : "Toolkit"


plot_top_and_bottom_n: True
plot_n: 10