name: ccre-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - snakemake>=9
  - snakemake-executor-plugin-slurm
  - bedtools
  - polars
  - pandas
  - numpy
  - bioframe
  - requests
