executor: slurm
jobs: 100
latency-wait: 60
rerun-incomplete: true
printshellcmds: true
keep-going: true

default-resources:
  slurm_partition: "12hours"
  mem_mb: 8000
  runtime: 120
  cpus_per_task: 1

set-resources:
  ENCODE_prepare_peaks:
    mem_mb: 32000
    runtime: 10
    slurm_partition: "30mins"
    cpus_per_task: 4
    
  CUSTOM_prepare_peaks:
    mem_mb: 32000
    runtime: 30
    cpus_per_task: 4
    slurm_partition: "30mins"
    
  merge_preped_peaks:
    mem_mb: 8000
    runtime: 10
    cpus_per_task: 2
    slurm_partition: "30mins"
    
  ATAC_cluster_rPeaks:
    mem_mb: 32000
    runtime: 30
    cpus_per_task: 8
    slurm_partition: "30mins"

  ATAC_filter_rPeaks:
    mem_mb: 64000
    runtime: 30
    cpus_per_task: 4
    slurm_partition: "30mins"    
    
  ENCODE_Zscore_across_bw:
    mem_mb: 8000
    runtime: 20
    cpus_per_task: 2
    slurm_partition: "30mins"
    
  CUSTOM_Zscore_across_bw:
    mem_mb: 8000
    runtime: 20
    cpus_per_task: 2
    slurm_partition: "30mins"
    
  call_maxZ_ATAC:
    mem_mb: 64000
    runtime: 60
    cpus_per_task: 8
    slurm_partition: "4hours"

  call_maxZ_DNase:
    mem_mb: 64000
    runtime: 60
    cpus_per_task: 8
    slurm_partition: "4hours"

  ENCODE_Zscore_across_DNase:
    mem_mb: 8000
    runtime: 20
    cpus_per_task: 2
    slurm_partition: "30mins"
    

  add_new_anchors:
    mem_mb: 8000
    runtime: 10
    cpus_per_task: 2
    slurm_partition: "30mins"
    
    
    
